networks:
  network-zabbix:
    driver: bridge
  public:
    external: true

services:
  postgres:
    container_name: postgres
    image: postgres:17.4
    shm_size: 128mb
    networks:
      - network-zabbix
    volumes:
      - 'zabbix_ph_data:/var/lib/postgresql/data'
    secrets:
      - zabbix-passwd
    restart: always
    environment:
      POSTGRES_DB: zabbix
      POSTGRES_USER: zabbix
      POSTGRES_PASSWORD_FILE: /run/secrets/zabbix-passwd
      PGDATA: /var/lib/postgresql/data/pgdata

  zabbix-server:
    container_name: zabbix-server
    image: zabbix/zabbix-server-pgsql:alpine-7.2.5
    networks:
      - network-zabbix
    links:
      - postgres
    restart: always
    ports:
      - '64343:10051'
    secrets:
      - zabbix-passwd
    environment:
      DB_SERVER_HOST: postgres
      DB_SERVER_PORT: 5432
      POSTGRES_DB: zabbix
      POSTGRES_USER: zabbix
      POSTGRES_PASSWORD_FILE: /run/secrets/zabbix-passwd
    depends_on:
      - postgres

  zabbix-agent2:
    container_name: zabbix-agent2
    image: zabbix/zabbix-agent2:alpine-7.2.5
    privileged: true  # ← важный ключ
    restart: always
    network_mode: host  # ← нужен для доступа к сети хоста
    pid: host           # ← нужен для доступа к процессам хоста
    security_opt:
      - apparmor=unconfined
    volumes:
      - /sys:/sys:ro
      - /var/log:/var/log:ro
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      ZBX_SERVER_HOST: 127.0.0.1     # или IP/hostname сервера Zabbix
      ZBX_SERVER_PORT: 64343
      ZBX_HOSTNAME: agent-on-host

  zabbix-frontend:
    container_name: zabbix-frontend
    image: zabbix/zabbix-web-nginx-pgsql:alpine-7.2.5
    networks:
      - network-zabbix
      - public
    links:
      - postgres
    restart: always
    secrets:
      - zabbix-passwd
    environment:
      ZBX_SERVER_HOST: zabbix-server
      ZBX_SERVER_PORT: 10051
      DB_SERVER_HOST: postgres
      DB_SERVER_PORT: 5432
      POSTGRES_DB: zabbix
      POSTGRES_USER: zabbix
      POSTGRES_PASSWORD_FILE: /run/secrets/zabbix-passwd
      PHP_TZ: Asia/Ho_Chi_Minh
    depends_on:
      - postgres
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.zabbix-frontend.rule=Host(`zabbix.rubystay.vn`)"
      - "traefik.http.routers.zabbix-frontend.entrypoints=websecure"
      - "traefik.http.services.zabbix-frontend.loadbalancer.server.port=8080"
      - "traefik.http.routers.zabbix-frontend.tls.certresolver=myresolver"
secrets:
  zabbix-passwd:
    file: ./zabbix-passwd.txt

volumes:
  zabbix_ph_data:
