networks:
  network-zabbix:
    driver: bridge
  public:
    external: true

services:
  postgres:
    container_name: postgres
    image: postgres:17.4
    shm_size: 128mb
    networks:
      - network-zabbix
    volumes:
      - 'zabbix_ph_data:/var/lib/postgresql/data'
    secrets:
      - zabbix-passwd
    environment:
      POSTGRES_DB: zabbix
      POSTGRES_USER: zabbix
      POSTGRES_PASSWORD_FILE: /run/secrets/zabbix-passwd
      PGDATA: /var/lib/postgresql/data/pgdata

  zabbix-server:
    container_name: zabbix-server
    image: zabbix/zabbix-server-pgsql:alpine-7.2.5
    networks:
      - network-zabbix
    links:
      - postgres
    restart: always
    ports:
      - '64343:10051'
    secrets:
      - zabbix-passwd
    environment:
      DB_SERVER_HOST: postgres
      DB_SERVER_PORT: 5432
      POSTGRES_DB: zabbix
      POSTGRES_USER: zabbix
      POSTGRES_PASSWORD_FILE: /run/secrets/zabbix-passwd
    depends_on:
      - postgres

  zabbix-frontend:
    container_name: zabbix-frontend
    image: zabbix/zabbix-web-nginx-pgsql:alpine-7.2.5
    networks:
      - network-zabbix
      - public
    links:
      - postgres
    restart: always
    secrets:
      - zabbix-passwd
    environment:
      ZBX_SERVER_HOST: zabbix-server
      ZBX_SERVER_PORT: 10051
      DB_SERVER_HOST: postgres
      DB_SERVER_PORT: 5432
      POSTGRES_DB: zabbix
      POSTGRES_USER: zabbix
      POSTGRES_PASSWORD_FILE: /run/secrets/zabbix-passwd
      PHP_TZ: Asia/Ho_Chi_Minh
    depends_on:
      - postgres
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.zabbix-frontend.rule=Host(`zabbix.rubystay.vn`)"
      - "traefik.http.routers.zabbix-frontend.entrypoints=websecure"
      - "traefik.http.services.zabbix-frontend.loadbalancer.server.port=80"
      - "traefik.http.routers.zabbix-frontend.tls.certresolver=myresolver"
secrets:
  zabbix-passwd:
    file: ./zabbix-passwd.txt
